export interface User{
    id: String,
    firstName: String,
    lastName: String,
    role: String,
    email: String,
    password: String,
    idNumber: Number,
    birthday: Date,
    gender: String,
    civilStatus: String,
    workPhone: Number,
    homePhone: Number,
    cellphone: Number,
    personalEmail: String,
    homeAddress: String,
    city: String,
    jobType: String, 
    jobTitle: String,
    department: String, 
    leader: String
}